### ISSUE TITLE
Please add an SSH key to your GitHub Account

### ISSUE THREAD

**Issue by bor-real** [lightbeam24/CustomTube#109]
When I look at the commit history for this repository, all I see are version numbers. It looks like you are just developing on your machine and then using GitHub.com's upload feature. When you do this, it makes it harder for developers for me to contribute, and negates all of the benefits of using a VCS like Git anyway.

[Generating a new SSH key and adding it to the ssh-agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
[Adding a new SSH key to your GitHub account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)

P. S. It makes the contribution calendar thingy on your profile less green.

**Comment by lightbeam24** [comment]
I don't understand what any of this is. Is this supposed to change how I develop? Am I supposed to upload half-finished versions of new releases to GH? Admittedly I've only skimmed through those links so far since it's late, but it sounds complicated.

As a Linux user, I've used the command line a bit before, but I've never used "Git". I've heard the name many times before, and I know it has something to do with GitHub, but I've never actually used it, and thus, don't know how.

I'm not really looking for contributors anyway (having someone else working on this project sounds like it would complicate things immensely). The main reason CT is open source is so people can trust that it's not doing anything shady, and also so people can report bugs. Plus, developing it myself will give me more coding experience (I'm still learning, after all).

**Comment by bor-real** [comment]
You don't have to upload your half-finished versions to GitHub. You can commit every time and make a change. When you commit, it will not affect GH until you type `git push origin main`

**Comment by lightbeam24** [comment]
> You don't have to upload your half-finished versions to GitHub. You can commit every time and make a change.

So I commit every time I make a change??? That's exactly what I meant by half finished version. Often times when developing new versions of the extension I experiment with things, and sometimes those things get cut from the release. I don't wanna upload stuff until it's at least somewhat ready. I dunno, this doesn't seem to fit my workflow at all.

> When you commit, it will not affect GH until you type git push origin main

If it's not affecting the repo, then where is it even going then? And what's the point?

**Comment by bor-real** [comment]
Sorry
