### ISSUE TITLE
Weird glitch on hitchhiker and early polymer layouts.

### ISSUE THREAD

**Issue by DrBrad22** [lightbeam24/CustomTube#131]
For some reason, on hitchhiker and early polymer (2019 and 2020) layouts, certain elements, specifically the likes and subscribe button, go to the edge of the screen. With early hitchhiker themes, the like and dislike buttons and the like ratio bar go to the edge of the screen (pictured below). With layouts without individual like and dislike buttons, the subscribe button goes to the edge (too lazy to switch themes and take a screenshot lmao). This happens no matter if custom player size is on or off, and it might be a problem with loading in the page with theater mode on, though I don't think it is.
![image](https://github.com/lightbeam24/CustomTube/assets/136956759/0c7f15e5-5a94-4cfe-8ad9-5de59faca47e)

**Comment by DrBrad22** [comment]
The screenshot was taken with the 2014 theme on.

**Comment by lightbeam24** [comment]
This is an issue that more and more people are having, but I still can't reproduce it. It seems to be due to a YouTube experiment, but I don't have the slightest idea which one. Your only option for now is to use a different account or use YouTube signed out (because the experiment might only affect the account your currently using).

**Comment by DrBrad22** [comment]
Youtube with their forced fucking experiments. smh they never fail to disappoint.
