### ISSUE TITLE
Favicon Does Not Work.

### ISSUE THREAD

**Issue by DamianEbers** [lightbeam24/CustomTube#159]
The favicons in 1.2.7 don't work. Can you fix that?

**Comment by lightbeam24** [comment]
This was a Chromium exclusive issue that was fixed in 1.2.7.1.

The reason the fix isn't out yet is because the Chrome Web Store takes far longer to review extensions than addons.mozilla.org: 

![Screenshot 2024-01-25 123640](https://github.com/lightbeam24/CustomTube/assets/105595945/92c02270-9b48-4dbf-a23c-a762f53f1462)

**Comment by DamianEbers** [comment]
thanks!

**Comment by lightbeam24** [comment]
Unpinned because the update has been approved now.
