### ISSUE TITLE
(suggestion) Theater for 2012 Theme

### ISSUE THREAD

**Issue by lovebug0706** [lightbeam24/CustomTube#173]
I found a video that had the theater theme from 2012 turned on for a split second. Heres the original video where it came from: https://www.youtube.com/watch?v=1cLMc5jPpH8
![The 2012 theater](https://github.com/lightbeam24/CustomTube/assets/34926216/b7a63699-a769-4aef-8c93-3a8876df1e6a)
Maybe some time you can implement this, some day. Thank you!

**Comment by lightbeam24** [comment]
This is an entirely different layout (the mid 2011 beta version of Cosmic Panda) that is currently not planned. A big part of this layout is the ability to choose multiple player sizes on the fly, which is too risky to implement due to how YouTube's modern website works. One update could completely break the layout beyond repair.

Also, supporting theater mode (or anything similar) on pre-2014 layouts **would require reworking a significant portion of the extension**, and could very likely cause major issues elsewhere, so that's why this is not planned at the moment.
