### ISSUE TITLE
The watch page is in some places glitched

### ISSUE THREAD

**Issue by Patricek0056** [lightbeam24/customtube#18]
### Problem description:
- In some languages (In my case Slovak/Slovenčina) in comments the reply button (“Reply” is “Odpovedať” in Slovak language) overlaps the like button.
- Also the “Show less” line (in video description) is overlapping the video description.

### Expected results:
- The reply button shouldn't overlap the like button in comments in Slovak (Slovenčina) language, nor in any other language.
- The “Show less” line shouldn't overlap the video description.

### Other details:
- Browser version: Firefox v113.0.2
- YouTube site zoom percentage: 100%
- YouTube layout: 2012 layout.
- OS version: Windows 11 22621.1778
- OS architecture: 64-bit
- Browser architecture: 64-bit
- CPU: AMD A10-7860K
- RAM: 16,0GB DDR3
- Motherboard: MSI A88XM-E35 V2
- Graphics: 1024MB ATI AMD Radeon R7

### Screenshots:
- I didn't click on anything (Only to stop video), this page is as is (untouched).
![The watch page is in some places glitched](https://github.com/lightbeam24/customtube/assets/69351811/babab5bd-1143-403e-bce6-fddbf90b09f6)

**Comment by Patricek0056** [comment]
Also, where is the original comment layout? Look at the screenshot earlier and look at this screenshot:
![image](https://github.com/lightbeam24/customtube/assets/69351811/53d0df74-6d38-444f-b4a6-ec3cd53dec9e)

**Comment by lightbeam24** [comment]
> The reply button shouldn't overlap the like button in comments in Slovak (Slovenčina) language, nor in any other language.

Yeah, see, CustomTube only truly supports English at the moment. I have already fixed a major bug that happened in every language other than English, but supporting every language individually is something that is going to be very difficult to do, since I only speak English.

I do have an idea for how to fix the reply button specifically in other languages though.

> The “Show less” line shouldn't overlap the video description.

Make sure you click the "Show more" button itself. Clicking the description itself also expands the description, just like in regular YouTube. I don't know how to explain it properly so here's some screenshots (took a random video for the description):

This happens when you click on the description (NOT the "Show more" button):

![clicked on desc](https://github.com/lightbeam24/customtube/assets/105595945/50c1eac8-fad3-4e11-a7c4-b3aeb33cb984)

This happens when you click on the "Show more" button specifically:

![clicked on btn](https://github.com/lightbeam24/customtube/assets/105595945/ae88c7bf-224f-4359-803c-48911745740b)

I don't know why this happens, and fixing it is not really a priority.

> Also, where is the original comment layout? Look at the screenshot earlier and look at this screenshot (It is thing for another issue, anyways sorry for off-topic):

It's planned. See, CustomTube was released because I felt like it was "good enough" for general use, but it is not actually finished. Any inaccuracy in CustomTube is something I'm most likely aware of, but haven't gotten around to yet.

**Comment by Patricek0056** [comment]
Thank you, that you will implement old comments! Good luck with implementing old comments (And mainly good luck with all your work).

**Comment by lightbeam24** [comment]
> And I said:
> 
> > I think, that the original 2012 comments layout would be probably possible with CSS, but the comments pages “1, 2, 3, 4, 5, 6, 7, Next>>” would need JavaScript.
> 
> I'm right?

Yes. I'm not sure if I'll even be implementing the pagination.

**Comment by lightbeam24** [comment]
> And, you are planning to implement JavaScript someday to CustomTube? Because this is using only CSS.

Incorrect, the extension is already 27.5% JavaScript. Plus, I've already "Implemented JavaScript" in some ways. For example:

![CustomElements](https://github.com/lightbeam24/customtube/assets/105595945/627131dc-0c4c-4717-b225-55267047f785)

That is not YouTube's regular view count element. CustomTube created it using JavaScript. Same with the Like to Dislike bar.

**Comment by lightbeam24** [comment]
> Then sorry. But similarity to real layout is important, so I think, that the pagination should be implemented.

Yes, a 100% accurate recreation would be ideal, but It might not be feasible. The reason I'm not guaranteeing pagination is because I've already tried to disable infinite scrolling on the comments (which would add a "Show more" button), but it proves to be more difficult than disabling the infinite scrolling of the related videos section for example.

If disabling infinite scrolling is hard, then pagination will be even harder.

**Comment by Patricek0056** [comment]
This is beginning to feels like a discussion to me (this issue), because there are 9 comments.
Anyways, can I create a new issue about these old (o.g.) comments to have better tracking of it?

**Comment by lightbeam24** [comment]
I mean you can if you want, but I mean, I'm already aware it. In fact, most of the things you brought up are things I was already aware of. The big exception being the PocketTube thing.

**Comment by Patricek0056** [comment]
So, I decided to create that issue, so at least we could have better control of it (e.g. If you accidentally forgot about that; Or if someone doesn't know, what feature you have to plan).

I will add a “Feature request:” pre-fix to it.

**Comment by Patricek0056** [comment]
> Yeah, see, CustomTube only truly supports English at the moment. I have already fixed a major bug that happened in every language other than English, but supporting every language individually is something that is going to be very difficult to do, since I only speak English.

That is not a language issue, but a CSS issue, because the “Odpovedať” is a longer word than “Reply”.

**Comment by lightbeam24** [comment]
> “Odpovedať” is a longer word than “Reply”.

That's exactly why it's a language issue. I'm not going to fix the CSS on this tiny button for each individual language. I've decided on a much easier fix.

Anyway, the fix I've decided on: 

YouTube has 2 reply buttons on the comments, a left one and a center one. The center one is shown by default, and CustomTube hides the center one, and shows the left one. Since the left one is unused by YouTube, it's not really implemented properly, which is why this issue exists. 

I've decided that for all languages besides English, I'm going to hide the Left Reply Button and just show the center one. It's less accurate, but I feel not much is lost by doing it that way.

**Comment by lightbeam24** [comment]
> “Odpovedať” is a longer word than “Reply”.

That's exactly why it's a language issue.

The fix I've decided on:

CustomTube adds CSS which puts the reply button on the left, rather than the right. I now realize that the method it uses is not practical for multiple languages though. So I've decided that for all languages other than English, the reply button will stay on the end on the comment, as it is in regular YouTube. Less accurate, but only slightly.

**Comment by lightbeam24** [comment]
The reply button fix has been applied in update 1.0.4. Should I close the issue?

**Comment by Patricek0056** [comment]
Yes, it is fixed. And for the “show less”, then it was caused by “Enhancer for YouTube” extension, so I disabled that feature which was glitching it.

**Comment by lightbeam24** [comment]
Alright, thanks.
