### ISSUE TITLE
Several issues with the Stargazer layout

### ISSUE THREAD

**Issue by MrIceblock** [lightbeam24/CustomTube#185]
Several elements are inaccurate (e.g., the comments section).
![image](https://github.com/lightbeam24/CustomTube/assets/69524536/f2d1aea4-eca8-40c4-acd4-51830b602840)
![image](https://github.com/lightbeam24/CustomTube/assets/69524536/c3304c57-af45-427f-a9ec-25cfcf806ac5)
[Snapshot from late 2008 for comparison:](https://web.archive.org/web/20081104044145/http://www.youtube.com/watch?v=dAI9mF_cBu0)
![image](https://github.com/lightbeam24/CustomTube/assets/69524536/5b1f4f6d-ac50-45de-b701-28f946e9152e)
![image](https://github.com/lightbeam24/CustomTube/assets/69524536/87286600-a797-41cc-b7b1-4e874e52f9bf)

**Comment by lightbeam24** [comment]
I'm closing this issue for the following reasons:

1. This isn't a bug, but an inaccuracy (and it's one that I am well aware of)
2. This issue is far too vague, there is no way to know when to close it (the conditions for closing it may never truly be met)

But just a couple things to note:

Several of the inaccuracies on the right side of the page will be fixed in 1.3.0 due to the replaced HTML. However, the comments will not be affected since it would not be a good idea to replace their HTML right now.
