### ISSUE TITLE
[Mozilla add-ons site] You have wrong order of the screenshots in addons.mozilla.org

### ISSUE THREAD

**Issue by Patricek0056** [lightbeam24/customtube#22]
Actual order of screenshots: 2019 > 2016 > 2017 > 2013 > 2012

Expected order of screenshots: 2019 > 2017 > 2016 > 2013 > 2012

Here: https://addons.mozilla.org/en-CA/firefox/addon/customtube/

**Comment by lightbeam24** [comment]
That was a deliberate decision. There a 4 watch page screenshots and 1 homepage screenshot. I thought it would look better with the homepage screenshot in the middle.

Please slow down with the issues. The majority of them are issues that I'm aware of and/or are not a big deal.

**Comment by lightbeam24** [comment]
The real problem I have here is the sheer amount of issues you've created in the past day or two.  

Not every little "problem" needs it's own issue. It floods the issue page, and makes it very unorganized, which is not very helpful. It's also pretty annoying honestly. If truly feel the need to point out all these issues, I'd recommend you make one or two issues that cover everything.

A perfect example of this would be #10, which pointed out several things in just one issue, instead of creating like 10 separate issues.

How about this: Make one issue for bugs, and another issue for Feature requests. If you do it that way, it would be much more helpful. I'm not saying never create new issues, but most of your issues have fallen into one of these two categories anyway, with the exception of the PocketTube one, which was definitely worth it's own issue.

You can leave the current issues as is.

**Comment by lightbeam24** [comment]
> But issues should be reported.

You're right, I'm sorry for my last statement. I guess I was feeling pressured to respond to all the issues as quickly as possible, which is just putting unnecessary stress on myself. That's probably the real reason I was getting annoyed. Really, this is my first time having a project that so many people care about, so I guess I'm still figuring out how exactly I'm supposed to run it. 

But I definitely shouldn't be stopping people from reporting issues. I realize that now.

I would still encourage you to include multiple similar issues in one single issue (#22 and #23 would've been better as a single issue), but if you can't, that's fine. Just understand that it might take a day or 2 for me to respond from now on.

I'm also thinking of making a list of issues I know about. Is that a good idea?

**Comment by Patricek0056** [comment]
Fine, and if the issue won't be an issue, but question, then I will post it rather to “Discussions”.

And if two issues would be similar, then I will rather open a single issue.

> I'm also thinking of making a list of issues I know about. Is that a good idea?

Maybe meta bug would be good. Meta bugs should have prefix [Meta], and meta bugs are different than normal bugs.

Example of meta bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1751505

**Comment by lightbeam24** [comment]
> Fine, and if the issue won't be an issue, but question, then I will post it rather to “Discussions”.

> And if two issues would be similar, then I will rather open a single issue.

Sounds good!

> Maybe meta bug would be good. Meta bugs should have prefix [Meta], and meta bugs are different than normal bugs.

> Example of meta bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1751505

Okay, I'll consider that.
