### ISSUE TITLE
View counter doesn't work on live streams

### ISSUE THREAD

**Issue by GemplelyTivadar** [lightbeam24/customtube#25]
It doesn't work on any of the custom layouts.
![2016](https://github.com/lightbeam24/customtube/assets/95102462/3ab04480-2564-4b29-b775-3ca020d8b88e)
![2014](https://github.com/lightbeam24/customtube/assets/95102462/cd1e1f63-fc51-4a90-b189-19c9f8ef8dec)
![2012](https://github.com/lightbeam24/customtube/assets/95102462/f303a6cc-ec02-40d8-9623-52ee3875d59f)
![2019](https://github.com/lightbeam24/customtube/assets/95102462/7eea72ff-3510-47e9-afc5-c1fa94c66bb8)

It only works when the "Disabled (Use Current YouTube Layout)" option is selected.
![disabled](https://github.com/lightbeam24/customtube/assets/95102462/9376e156-4e89-4887-9421-801276c44cff)

**Comment by lightbeam24** [comment]
Thanks for reporting this. Because of the changes the latest update (1.0.4) made, I know this is a newly introduced bug. I'm not exactly sure how to fix this yet, but I'll look into it.

**Comment by lightbeam24** [comment]
Okay, so I actually found a way to fix this, as well as pretty much all live stream related issues that CustomTube has had since it first released (view count and "started streaming x time ago" wouldn't update). While I've already started working on the next real update, I'm going to release V1.0.4.1 with this fix included.
