### ISSUE TITLE
Search Filter button in the wrong place while searching

### ISSUE THREAD

**Issue by gameshowrecaps** [lightbeam24/CustomTube#29]
Search filter is supposed to be to the left. (It also now opens a screen with the search filters instead of just displaying them)
![Screenshot 2023-06-21 230640](https://github.com/lightbeam24/customtube/assets/57842610/7affb5e7-6028-456a-84b4-f328fbb750f0)

**Comment by lightbeam24** [comment]
This is a new change that YouTube is A/B testing (it's called "Search Header" I believe). It's not caused by the extension.

I plan to try to make CustomTube work with Search Header in the future, though I'm not sure if it will be possible to fully fix it (the filters window in particular might be difficult to fix).

**Comment by gameshowrecaps** [comment]
I'm late but I can confirm they are A/B testing this. My alt has filters in the normal place and my main has it to the right. I haven't heard anybody talking about this anywhere.

**Comment by lightbeam24** [comment]
They're also A/B testing another version of Search Header with a filter bar. I would assume (hope) this is the version that they plan on going with, because otherwise it is a completely pointless change. Either way, Search Header in general is the reason why CustomTube doesn't affect search filters yet (why bother styling the old search filters when I know they're gonna replace it).

![searchheadr](https://github.com/lightbeam24/CustomTube/assets/105595945/29a8fbf4-63bf-4a35-afc7-f304b6a7c70c)

**Comment by gameshowrecaps** [comment]
And it has happened finally for me and my alt. They went for the version posted above.

**Comment by lightbeam24** [comment]
Yes, it seems they've rolled it out to most people if not everyone by now. I'm currently trying to think of how exactly to go about fixing this. I personally don't think the addition of the chip bar is a terrible change, and am considering keeping it in, or at least making it optional. The big problem though will be the filters menu itself, which will probably remain a window for a while until I find a way to fix that.

No matter what I decide to do, the filters button will be moved back to the left.

**Comment by lightbeam24** [comment]
This was fixed a while ago.
