### ISSUE TITLE
Early 2013 and 2013 watch page has a strange issue

### ISSUE THREAD

**Issue by thoudankeykang** [lightbeam24/CustomTube#33]
![image](https://github.com/lightbeam24/CustomTube/assets/89052168/9f74b3fa-2bfe-4c9f-b48d-2805e62734f0)

everything is all sorts of mixed together

**Comment by lightbeam24** [comment]
Some others reported having this issue, but I'm not sure what the cause or fix is, since it doesn't happen to me or most other people. Could you answer these questions?

1. Do you have Return YouTube Dislike installed? This will always happen if you have "Enable Return YouTube Dislike compatibility" on without having Return YouTube Dislike installed. I assume this probably isn't the issue though.

2. Did this happen before, or did it just start happening now? (Unless you just started using the extension)

3. Does it happen if you go into a Private Window?

4. Does it stay like that, or does it fix itself after a few seconds? (Like this: https://imgur.com/a/1sG6ygn) If so, this isn't a bug.

5. Does the 2017 layout load properly?

**Comment by thoudankeykang** [comment]
disabling return youtube dislike compatibility fixed it, thanks!
![image](https://github.com/lightbeam24/CustomTube/assets/89052168/ef8fd01c-f742-450d-af91-75df9f9cab7d)

**Comment by TorutheRedFox** [comment]
same thing happens on 2014 layout it seems too

**Comment by lightbeam24** [comment]
> same thing happens on 2014 layout it seems too

Did you follow all the steps I said in my other comment?
