### ISSUE TITLE
Not all icons match to the selected layout

### ISSUE THREAD

**Issue by Caddy8970** [lightbeam24/CustomTube#39]
![immagine](https://github.com/lightbeam24/CustomTube/assets/113631055/b60b42c1-ecd0-47cc-8927-8e532fd54b09)
Some icons use the current (2023) style, others use the selected one.

Layout: 2019
Version: `1.0.4.4`

**Comment by lightbeam24** [comment]
I'm working to improve this in the next update. Here's a screenshot of the 2019 layout homepage in my unfinished version of version 1.1.0 (the next update):

![Screenshot_2023-07-17_11-17-44](https://github.com/lightbeam24/CustomTube/assets/105595945/62ef0543-54f5-488f-9171-e8b5bb20c2ae)

I'm not sure if all the old icons will be restored in version 1.1.0 since I have to replace them one by one, but I've already restored many of them as you can see.
