### ISSUE TITLE
Time stamps on thumbnails are having some sort of transparent rectangle behind them.

### ISSUE THREAD

**Issue by GemplelyTivadar** [lightbeam24/CustomTube#45]
Happens while using layouts 2012 - 2017.
Both stable and beta version of the extension are affected.

![timestamp 1](https://github.com/lightbeam24/CustomTube/assets/95102462/17445dd3-3203-4572-ac3b-264b46bdf82b)

**Comment by lightbeam24** [comment]
Yep, thanks. YouTube changed some stuff. That's a serious enough issue for me to release another patch for 1.0.4. Hopefully it'll be the last one. I don't think I'll be releasing another beta for 1.1.0 though, since I just released Beta 3 yesterday (and will hopefully be releasing stable 1.1.0 soon), so you can put this CSS into a userstyle to fix it:

```
html[layout]:not([layout^="polymer"]) ytd-thumbnail-overlay-time-status-renderer ytd-badge-supported-renderer {
  display: none;
}
html[layout]:not([layout^="polymer"]) ytd-thumbnail #overlays ytd-thumbnail-overlay-time-status-renderer {
  margin: 1px !important;
  border-radius: unset;
  padding: unset;
  font-size: unset;
  font-weight: unset;
  background: unset;
  letter-spacing: unset;
}
html[layout]:not([layout^="polymer"]) #time-status.ytd-thumbnail-overlay-time-status-renderer {
  margin: 2px;
  border-radius: 0 !important;
  padding: 1px 4px;
  font-size: 11px;
  font-weight: 700;
  background: rgba(0,0,0,.75);
  letter-spacing: 0;
}
```

**Comment by GemplelyTivadar** [comment]
Yeah, I figured it could be a YouTube update that caused this. Thanks for the CSS.

**Comment by lightbeam24** [comment]
Update 1.0.4.5 is live now with the fix.
